# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  ## Bundler
  # - package-ecosystem: "bundler"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  ## Dockerfile
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #       interval: "daily"

  ## GitHub Actions
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  ## Composer
  # - package-ecosystem: "composer"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  ## Go modules
  # - package-ecosystem: "gomod"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  ## pip
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  ## Terraform
  # - package-ecosystem: "terraform"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  ## Cargo
  # - package-ecosystem: "cargo"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"

  ## Mix
  # - package-ecosystem: "mix"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
